---
ansible_user: username

shell_configure: true
shell_starship_configure: true
shell_zsh_path: /usr/bin/zsh

apt_configure: true
apt_nano_configure: true
apt_git_configure: true
apt_curl_configure: true
apt_qemu_configure: true

timezone_configure: true
timezone_value: Asia/Taipei
