---
- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible version (>= 2.11)
      ansible.builtin.assert:
        that: ansible_version.full is version('2.11', '>=')
        msg: "Ansible version must be >= 2.11"

- name: Prepare Ubuntu environment
  hosts: ubuntu
  gather_facts: true
  roles:
    - role: timezone
      when: timezone_configure
    - role: apt
      when: apt_configure
    - role: shell
      when: shell_configure
